# Generated by Django 3.2.7 on 2022-01-04 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Javob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.CharField(max_length=200)),
                ('togri', models.BooleanField(max_length=200)),
                ('savol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.savol')),
            ],
        ),
    ]
